name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
          versionSpec: '5.x'
          
    - name: Check out Code 
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.11
      with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build Squazz.Sugar.sln --configuration release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
      
    - name: Test
      run: dotnet test --configuration release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} --no-build --verbosity normal
                
    - name: Package nuget
      run: dotnet pack Squazz.Sugar.sln --configuration release --include-symbols --include-source -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}
      
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./package/*.nupkg --source https://nuget.pkg.github.com/threenine/index.json --api-key ${{ github.token }}
      
#    - name: Push generated package to Nuget.org
#      run: dotnet nuget push ./package/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
